### ISSUE TITLE
can you discriple how to debug this project?

### ISSUE THREAD

**Issue by tianhaichen** [NaiJii/Finite-Elements#1]
when I debug this project,I got this error。I don't know how to fixed it.

![image](https://github.com/NaiJii/Finite-Elements/assets/31316140/56dbd232-84e2-4966-be67-a24b2774c65c)

**Comment by NaiJii** [comment]
Sorry I don't remember, this is a homework project for my university classes.
https://gmsh.info/ this is the library you'll need to use for this.

**Comment by tianhaichen** [comment]
thanks. the problem is solved
________________________________
发件人: jii ***@***.***>
发送时间: 2024年3月21日 12:40
收件人: NaiJii/Finite-Elements ***@***.***>
抄送: cz ***@***.***>; Author ***@***.***>
主题: Re: [NaiJii/Finite-Elements] can you discriple how to debug this project? (Issue #1)


Closed #1<https://github.com/NaiJii/Finite-Elements/issues/1> as completed.

―
